#!/usr/bin/env bash
# Build HexBee.app — a double-clickable macOS launcher for the Hive dashboard
# and the Comb triage UI.
#
#   bash scripts/make-macos-app.sh              # -> ~/Applications/HexBee.app
#   bash scripts/make-macos-app.sh --dest /Applications
#
# The app owns the servers it starts: Quit the app and both UIs stop with it.
# No terminal stays open, and nothing is left listening afterwards.
#
# Built as an AppleScript applet rather than a shell-script bundle, because
# only a real applet receives the Dock's Quit event. A bundle wrapping a bash
# script cannot be quit — macOS falls back to Force Quit, which SIGKILLs the
# launcher and leaves the servers running, which is the exact failure this is
# supposed to prevent.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$HOME/Applications"

# pipx's bin dir may not be on PATH in a fresh shell; the launcher adds it too.
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

while [ $# -gt 0 ]; do
    case "$1" in
        --dest) DEST="$2"; shift ;;
        -h|--help) sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $1 (try --help)" >&2; exit 2 ;;
    esac
    shift
done

if [ "$(uname -s)" != "Darwin" ]; then
    echo "This builds a macOS .app bundle; it only makes sense on macOS." >&2
    exit 1
fi

APP="$DEST/HexBee.app"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "==> Building $APP"
mkdir -p "$DEST"
rm -rf "$APP"

# -- control script --------------------------------------------------------
# All the real work. The applet only calls this, so the logic stays in shell
# where it is readable and testable on its own:
#     .../HexBee.app/Contents/Resources/hexbee-ctl.sh status
cat > "$WORK/hexbee-ctl.sh" <<CTL
#!/bin/bash
# HexBee.app control script — generated by scripts/make-macos-app.sh
REPO_ROOT="$REPO_ROOT"
CTL

cat >> "$WORK/hexbee-ctl.sh" <<'CTL'
HIVE_PORT=8080
COMB_PORT=8091
LOG_DIR="$HOME/Library/Logs/HexBee"
STATE_DIR="$HOME/Library/Application Support/HexBee"
PID_FILE="$STATE_DIR/app.pids"

mkdir -p "$LOG_DIR" "$STATE_DIR"

# Load an optional env file so the ingest key is not baked into the bundle:
#   echo 'HEXBEE_INGEST_KEY=...' > ~/.hexbee-app.env
[ -f "$HOME/.hexbee-app.env" ] && . "$HOME/.hexbee-app.env"

# Default the data dir into Application Support, not the repo. macOS denies a
# double-clicked app access to ~/Downloads, ~/Desktop and ~/Documents (TCC),
# and the failure is a bare "Operation not permitted" with no prompt. Keeping
# both the code and the evidence out of those folders is what makes this work
# from a double-click at all.
export HEXBEE_DATA_DIR="${HEXBEE_DATA_DIR:-$STATE_DIR}"
export HEXBEE_INGEST_KEY="${HEXBEE_INGEST_KEY:-devkey}"
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"

port_busy() { lsof -nP -iTCP:"$1" -sTCP:LISTEN >/dev/null 2>&1; }

# Prefer the pipx-installed copies: their code lives under Application
# Support, which the app can always read. The repo venv is the fallback for
# development, and only works if the repo is outside a protected folder.
resolve() {  # resolve <command>
    local found
    found="$(command -v "$1" 2>/dev/null || true)"
    if [ -n "$found" ] && [ -x "$found" ]; then echo "$found"; return 0; fi
    if [ -x "$REPO_ROOT/.venv/bin/$1" ]; then echo "$REPO_ROOT/.venv/bin/$1"; return 0; fi
    return 1
}

start() {
    # Self-heal after a Force Quit: clear anything a previous run orphaned.
    stop_quiet

    local hive_bin comb_bin
    if ! hive_bin="$(resolve hexbee-hive)"; then
        # Nothing installed yet. Rather than telling someone who double-clicked
        # an app to go and type a pipx command, hand over to the bootstrapping
        # launcher, which builds the environment and starts the Hive itself.
        if [ -f "$REPO_ROOT/scripts/hexbee_launcher.py" ] && command -v python3 >/dev/null 2>&1; then
            echo "first run — building the environment" >&2
            python3 "$REPO_ROOT/scripts/hexbee_launcher.py" --no-browser \
                >>"$LOG_DIR/bootstrap.log" 2>&1 &
            local i
            for i in $(seq 1 240); do
                port_busy "$HIVE_PORT" && break
                sleep 0.5
            done
            port_busy "$HIVE_PORT" && { open "http://127.0.0.1:$HIVE_PORT/"; return 0; }
        fi
        echo "cannot find hexbee-hive — install it with: pipx install \"$REPO_ROOT/hive\"" >&2
        return 1
    fi

    if port_busy "$HIVE_PORT"; then
        # Something else owns the port. Do not adopt it and do not kill it.
        open "http://127.0.0.1:$HIVE_PORT/"
        return 0
    fi

    : > "$PID_FILE"
    "$hive_bin" web >>"$LOG_DIR/hive.log" 2>&1 &
    echo $! >> "$PID_FILE"

    if comb_bin="$(resolve hexbee-comb)" && ! port_busy "$COMB_PORT"; then
        "$comb_bin" serve --port "$COMB_PORT" >>"$LOG_DIR/comb.log" 2>&1 &
        echo $! >> "$PID_FILE"
    fi

    # Wait for the dashboard to answer rather than guessing with sleep.
    local i
    for i in $(seq 1 40); do
        port_busy "$HIVE_PORT" && break
        sleep 0.25
    done

    if ! port_busy "$HIVE_PORT"; then
        local hint=""
        if grep -q "Operation not permitted" "$LOG_DIR/hive.log" 2>/dev/null; then
            hint=$'\n\nmacOS blocked access to a protected folder. Move the project out of Downloads, Desktop or Documents, or run: pipx install '"$REPO_ROOT/hive"
        fi
        echo "The Hive did not start. See $LOG_DIR/hive.log$hint" >&2
        return 1
    fi

    open "http://127.0.0.1:$HIVE_PORT/"
    return 0
}

stop_quiet() {
    [ -f "$PID_FILE" ] || return 0
    local pid
    while read -r pid; do
        [ -n "$pid" ] && kill "$pid" 2>/dev/null || true
    done < "$PID_FILE"
    # Give them a moment to close the SQLite WAL cleanly, then insist.
    sleep 1
    while read -r pid; do
        [ -n "$pid" ] && kill -9 "$pid" 2>/dev/null || true
    done < "$PID_FILE"
    rm -f "$PID_FILE"
}

status() {
    port_busy "$HIVE_PORT" && echo "hive:  running on $HIVE_PORT" || echo "hive:  stopped"
    port_busy "$COMB_PORT" && echo "comb:  running on $COMB_PORT" || echo "comb:  stopped"
    [ -f "$PID_FILE" ] && echo "pids:  $(tr '\n' ' ' < "$PID_FILE")"
    echo "data:  $HEXBEE_DATA_DIR"
    echo "logs:  $LOG_DIR"
}

case "${1:-}" in
    start)  start ;;
    stop)   stop_quiet ;;
    status) status ;;
    *) echo "usage: $(basename "$0") {start|stop|status}" >&2; exit 2 ;;
esac
CTL

# -- applet ----------------------------------------------------------------
# Compiled with `osacompile -s` (stay-open). Without it the applet exits the
# moment `on run` returns — which fires `on quit`, which stops the servers it
# had just started. The `on idle` handler is what a stay-open applet loops on.
cat > "$WORK/HexBee.applescript" <<'APPLESCRIPT'
on ctl(action)
	set helper to quoted form of (POSIX path of (path to resource "hexbee-ctl.sh"))
	try
		do shell script helper & " " & action
	on error errMsg
		if action is "start" then
			display alert "HexBee" message errMsg as critical
			quit
		end if
	end try
end ctl

on run
	ctl("start")
end run

on idle
	return 30
end idle

on quit
	ctl("stop")
	continue quit
end quit
APPLESCRIPT

osacompile -s -o "$APP" "$WORK/HexBee.applescript"
cp "$WORK/hexbee-ctl.sh" "$APP/Contents/Resources/hexbee-ctl.sh"
chmod +x "$APP/Contents/Resources/hexbee-ctl.sh"

# -- icon ------------------------------------------------------------------
# applet.icns is the name the applet's own Info.plist already points at, so
# overwriting it is all that is needed to rebrand the bundle.
LOGO="$REPO_ROOT/hive/hexbee_hive/static/logo-512.png"
if [ -f "$LOGO" ] && command -v iconutil >/dev/null 2>&1; then
    ICONSET="$WORK/HexBee.iconset"
    mkdir -p "$ICONSET"
    for size in 16 32 128 256 512; do
        sips -z $size $size "$LOGO" --out "$ICONSET/icon_${size}x${size}.png" \
            >/dev/null 2>&1 || true
        double=$((size * 2))
        sips -z $double $double "$LOGO" \
            --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null 2>&1 || true
    done
    if iconutil -c icns "$ICONSET" -o "$WORK/HexBee.icns" 2>/dev/null; then
        cp "$WORK/HexBee.icns" "$APP/Contents/Resources/applet.icns"
        echo "    icon built from logo-512.png"
    else
        echo "    icon build failed — the app still works, generic icon"
    fi
else
    echo "    no logo found — using the generic applet icon"
fi

# -- bundle identity -------------------------------------------------------
PLIST="$APP/Contents/Info.plist"
set_key() { /usr/libexec/PlistBuddy -c "Set :$1 $2" "$PLIST" 2>/dev/null \
            || /usr/libexec/PlistBuddy -c "Add :$1 string $2" "$PLIST" >/dev/null; }
set_key CFBundleName "HexBee"
set_key CFBundleDisplayName "HexBee Forensics"
set_key CFBundleIdentifier "io.hexbee.forensics"
set_key CFBundleVersion "0.1.0"
set_key CFBundleShortVersionString "0.1.0"

# osacompile ad-hoc signs the applet, and every edit above — the icon, the
# bundle identity — invalidates that signature. macOS then reports the app as
# "modified" and refuses to treat it as signed at all. Re-sign last.
#
# Ad-hoc (`-s -`) needs no Apple Developer account. It is not notarisation and
# does not silence Gatekeeper for a *downloaded* app; it does not need to,
# because this script builds the bundle locally and locally-built apps are
# never quarantined. That is the whole reason HexBee ships a build script
# rather than a DMG.
if codesign --force --deep --sign - "$APP" 2>/dev/null; then
    if codesign --verify --deep --strict "$APP" 2>/dev/null; then
        echo "    signed (ad-hoc) and verified"
    else
        echo "    signed, but verification failed — the app still runs" >&2
    fi
else
    echo "    could not sign — the app still runs locally" >&2
fi

# Register with LaunchServices so the icon and name show up immediately.
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP" >/dev/null 2>&1 || true
touch "$APP"

# A double-clicked app cannot read Downloads/Desktop/Documents without an
# explicit grant, and macOS denies it silently rather than prompting. Say so
# at build time rather than letting it surface as a blank window later.
if ! command -v hexbee-hive >/dev/null 2>&1; then
    case "$REPO_ROOT/" in
        "$HOME/Downloads/"*|"$HOME/Desktop/"*|"$HOME/Documents/"*)
            cat >&2 <<EOF

WARNING: this project sits in a folder macOS protects, and hexbee-hive is not
installed outside it. The app will fail to start with "Operation not
permitted". Fix it with:

  pipx install "$REPO_ROOT/hive"

EOF
            ;;
    esac
fi

cat <<EOF

Built: $APP

  Open it        double-click HexBee in $DEST (or: open "$APP")
  Dashboard      http://127.0.0.1:8080
  Comb UI        http://127.0.0.1:8091
  Quit           Cmd-Q, or right-click the Dock icon > Quit
                 — both UIs stop with it
  Evidence       ~/Library/Application Support/HexBee
  Logs           ~/Library/Logs/HexBee/

Check it from a terminal without opening the app:
  "$APP/Contents/Resources/hexbee-ctl.sh" status

Drag it to your Dock to keep it around. To use a real ingest key instead of
the demo one:

  echo 'HEXBEE_INGEST_KEY=your-key-here' > ~/.hexbee-app.env
EOF
